# config/aws.yml
defaults: &defaults
  s3_access_key_id:  # TODO access the AWS & get yours
  s3_secret_access_key:  # TODO access the AWS & get yours
  s3_region: sa-east-1
  s3_bucket: nitro-tst

development:
  <<: *defaults

test:
  <<: *defaults

production:
  s3_bucket: nitro-production