# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
development:
  secret_key_base: 017371644c26cbcde980d5c1d45fbf1c6eee374c5ea492a206bbc02ce6e337c3c95db8e23f5204b06ddb020ba8e48e27750ed15906ef19fe5be639a501de50e5

test:
  secret_key_base: 9b42ea9ed1068f7d60a15c665ee517a1d6e78d2596501ff974923e93b74dffb2a83dc3df8740aee051df89d7c5e62a3110d2783e9ecf97e92fabf399dd943d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mail:
    user_name: contato@nitrostart.me
    password: Nitrar2016*
  nitro_pay:
    app_id: 2
    secret_key: $2a$10$5trtC3S1ydgUjUr8PZbhi.uqjgRjgdnTvaZoWLjdWG0vixUozy13G
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
