# Define Locale Icons (translate word or expressions in default icon)
locale_icon:
  pitch:
    name: mdi-action-assignment-ind
  idea:
    main_problem: ion-alert-circled
    second_problems: ion-alert
    current_solution: ion-shuffle
    tag_line_pitch: ion-chatbox-working
    high_concept_pitch: ion-briefcase
    how_validate: ion-flag
  business:
    partnerships: ion-loop
    value_proposition: fa fa-gift
    revenue_model: mdi-action-trending-up
    costumer_success_stories: ion-thumbsup
  project:
    stage: ion-connection-bars
    patent: ion-flag
    awards: ion-trophy
  market:
    segment: ion-navigate
    currency_iso: mdi-editor-attach-money
    total_money: ion-arrow-swap
    formatted_total_money: ion-arrow-swap
    total_costumers: ion-ios-people
    formatted_total_costumers: ion-ios-people
    trends_insight: ion-ios-lightbulb-outline
    costumer_specification: ion-ios-paper-outline
  traction:
    grow_strategy: ion-android-locate
    conversion_cust: ion-cash
    formatted_conversion_cust: ion-cash
    daily_growth_rate: fa fa-line-chart
    formatted_daily_growth_rate: fa fa-line-chart
    costumer_channels: ion-speakerphone