# Define Locale Icons (translate word or expressions in default icon)
locale_icon:
  pitch:
    name: mdi-action-assignment-ind
    video_link: ion-social-youtube
  idea:
    main_problem: ion-alert-circled
    second_problems: ion-alert
    current_solution: ion-shuffle
    tag_line_pitch: ion-chatbox-working
    high_concept_pitch: ion-briefcase
    why_must_success: ion-ios-lightbulb
    how_validate: ion-flag
  business:
    partnerships: ion-loop
    value_proposition: fa fa-gift
    revenue_model: mdi-action-trending-up
    advantages: ion-thumbsup
    disadvantages: ion-thumbsdown
    main_product_price: ion-cash
    costumer_success_stories: ion-chatbox-working
  project:
    stage: ion-connection-bars
    patent: ion-flag
    patent_source: ion-link
    awards: ion-trophy
    award_source: ion-link
  market:
    segment: ion-navigate
    currency_iso: mdi-editor-attach-money
    total_money: ion-arrow-swap
    source_money: ion-link
    money_source_link: ion-link
    total_costumers: ion-ios-people
    source_costumer: ion-link
    costumers_source_link: ion-link
    trends_insight: ion-ios-lightbulb-outline
    costumer_specification: ion-ios-paper-outline
  traction:
    grow_strategy: ion-android-locate
    lead_cust: ion-ios-people
    conversion_cust: ion-android-contact
    daily_growth_rate: fa fa-line-chart
    costumer_channels: ion-speakerphone
    amount_daily_lead: ion-stats-bars
  financial:
    total_users: ion-ios-people
    total_costumers: ion-android-contacts
    total_revenue: fa fa-sign-in
    total_expense: fa fa-sign-out
    bootstrapped: ion-cash
    market_penetration: ion-pie-graph
  provider:
    name: mdi-action-account-circle
    segment: ion-navigate
    provides: fa fa-truck
    counterpart: ion-shuffle
  competitor:
    name: mdi-action-account-circle
    price: ion-ios-pricetag
    total_revenue: ion-cash
    total_costumers: ion-ios-people
    bad_stories: ion-sad
    success_stories: ion-android-contacts
    your_advantage: ion-android-star
  campaign:
    link: ion-link
  teammate:
    user: mdi-action-account-circle
    role: mdi-action-class
    expertise: ion-ribbon-b
    contacts: Possui Contatos?