require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FinancialsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Financial. As you add validations to Financial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FinancialsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all financials as @financials" do
      financial = Financial.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:financials)).to eq([financial])
    end
  end

  describe "GET #show" do
    it "assigns the requested financial as @financial" do
      financial = Financial.create! valid_attributes
      get :show, {:id => financial.to_param}, valid_session
      expect(assigns(:financial)).to eq(financial)
    end
  end

  describe "GET #new" do
    it "assigns a new financial as @financial" do
      get :new, {}, valid_session
      expect(assigns(:financial)).to be_a_new(Financial)
    end
  end

  describe "GET #edit" do
    it "assigns the requested financial as @financial" do
      financial = Financial.create! valid_attributes
      get :edit, {:id => financial.to_param}, valid_session
      expect(assigns(:financial)).to eq(financial)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Financial" do
        expect {
          post :create, {:financial => valid_attributes}, valid_session
        }.to change(Financial, :count).by(1)
      end

      it "assigns a newly created financial as @financial" do
        post :create, {:financial => valid_attributes}, valid_session
        expect(assigns(:financial)).to be_a(Financial)
        expect(assigns(:financial)).to be_persisted
      end

      it "redirects to the created financial" do
        post :create, {:financial => valid_attributes}, valid_session
        expect(response).to redirect_to(Financial.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved financial as @financial" do
        post :create, {:financial => invalid_attributes}, valid_session
        expect(assigns(:financial)).to be_a_new(Financial)
      end

      it "re-renders the 'new' template" do
        post :create, {:financial => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested financial" do
        financial = Financial.create! valid_attributes
        put :update, {:id => financial.to_param, :financial => new_attributes}, valid_session
        financial.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested financial as @financial" do
        financial = Financial.create! valid_attributes
        put :update, {:id => financial.to_param, :financial => valid_attributes}, valid_session
        expect(assigns(:financial)).to eq(financial)
      end

      it "redirects to the financial" do
        financial = Financial.create! valid_attributes
        put :update, {:id => financial.to_param, :financial => valid_attributes}, valid_session
        expect(response).to redirect_to(financial)
      end
    end

    context "with invalid params" do
      it "assigns the financial as @financial" do
        financial = Financial.create! valid_attributes
        put :update, {:id => financial.to_param, :financial => invalid_attributes}, valid_session
        expect(assigns(:financial)).to eq(financial)
      end

      it "re-renders the 'edit' template" do
        financial = Financial.create! valid_attributes
        put :update, {:id => financial.to_param, :financial => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested financial" do
      financial = Financial.create! valid_attributes
      expect {
        delete :destroy, {:id => financial.to_param}, valid_session
      }.to change(Financial, :count).by(-1)
    end

    it "redirects to the financials list" do
      financial = Financial.create! valid_attributes
      delete :destroy, {:id => financial.to_param}, valid_session
      expect(response).to redirect_to(financials_url)
    end
  end

end
