require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TractionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Traction. As you add validations to Traction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TractionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all tractions as @tractions" do
      traction = Traction.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:tractions)).to eq([traction])
    end
  end

  describe "GET #show" do
    it "assigns the requested traction as @traction" do
      traction = Traction.create! valid_attributes
      get :show, {:id => traction.to_param}, valid_session
      expect(assigns(:traction)).to eq(traction)
    end
  end

  describe "GET #new" do
    it "assigns a new traction as @traction" do
      get :new, {}, valid_session
      expect(assigns(:traction)).to be_a_new(Traction)
    end
  end

  describe "GET #edit" do
    it "assigns the requested traction as @traction" do
      traction = Traction.create! valid_attributes
      get :edit, {:id => traction.to_param}, valid_session
      expect(assigns(:traction)).to eq(traction)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Traction" do
        expect {
          post :create, {:traction => valid_attributes}, valid_session
        }.to change(Traction, :count).by(1)
      end

      it "assigns a newly created traction as @traction" do
        post :create, {:traction => valid_attributes}, valid_session
        expect(assigns(:traction)).to be_a(Traction)
        expect(assigns(:traction)).to be_persisted
      end

      it "redirects to the created traction" do
        post :create, {:traction => valid_attributes}, valid_session
        expect(response).to redirect_to(Traction.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved traction as @traction" do
        post :create, {:traction => invalid_attributes}, valid_session
        expect(assigns(:traction)).to be_a_new(Traction)
      end

      it "re-renders the 'new' template" do
        post :create, {:traction => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested traction" do
        traction = Traction.create! valid_attributes
        put :update, {:id => traction.to_param, :traction => new_attributes}, valid_session
        traction.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested traction as @traction" do
        traction = Traction.create! valid_attributes
        put :update, {:id => traction.to_param, :traction => valid_attributes}, valid_session
        expect(assigns(:traction)).to eq(traction)
      end

      it "redirects to the traction" do
        traction = Traction.create! valid_attributes
        put :update, {:id => traction.to_param, :traction => valid_attributes}, valid_session
        expect(response).to redirect_to(traction)
      end
    end

    context "with invalid params" do
      it "assigns the traction as @traction" do
        traction = Traction.create! valid_attributes
        put :update, {:id => traction.to_param, :traction => invalid_attributes}, valid_session
        expect(assigns(:traction)).to eq(traction)
      end

      it "re-renders the 'edit' template" do
        traction = Traction.create! valid_attributes
        put :update, {:id => traction.to_param, :traction => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested traction" do
      traction = Traction.create! valid_attributes
      expect {
        delete :destroy, {:id => traction.to_param}, valid_session
      }.to change(Traction, :count).by(-1)
    end

    it "redirects to the tractions list" do
      traction = Traction.create! valid_attributes
      delete :destroy, {:id => traction.to_param}, valid_session
      expect(response).to redirect_to(tractions_url)
    end
  end

end
